ref = LoadH5Seurat("LungMAP_Mouse.h5seurat")
ref = SCTransform(ref,method='glmGamPoi',vst.flavor='v2',vars.to.regress=c('pMT','G2M.Score','S.Score'),return.only.var.genes=FALSE,verbose=TRUE)
gc()
ref = RunPCA(ref,assay="SCT",npcs=50)
ref = RunUMAP(ref,assay="SCT",dims=1:50,return.model=TRUE)
def = AzimuthReference(ref,refDR="pca",dims=1:50,metadata = c("celltype_level1","celltype_level2","celltype_level3"))
SaveAnnoyIndex(object = def[["refdr.annoy.neighbors"]], file = file.path("/work/users/c/a/came/Analysis_SC_07.21.23/Pipeline4/lungmap_mouseref/idx.annoy"))
saveRDS(object = def, file = file.path("/work/users/c/a/came/Analysis_SC_07.21.23/Pipeline4/lungmap_mouseref/ref.Rds"))
#S_Combined.SCT = RunAzimuth(query=S_Combined.SCT,reference="spec_annot",assay="SCT",annotation.levels="celltype_level2")